'use client';

import { SecurityDepositLaw } from '@/data/securityDepositLaws';

interface ComplianceChecklistProps {
  law: SecurityDepositLaw;
}

export default function ComplianceChecklist({ law }: ComplianceChecklistProps) {
  const generateChecklist = (law: SecurityDepositLaw): string[] => {
    const checklist: string[] = [];

    // Max deposit check
    checklist.push(`Verify security deposit amount does not exceed: ${law.maxDeposit}`);

    // Interest requirements
    if (law.interestRequired) {
      checklist.push(`Set up interest-bearing account (Rate: ${law.interestRate || 'as required'})`);
      checklist.push('Track and pay accrued interest to tenant');
    }

    // Holding account
    if (law.holdingAccount !== 'No specific requirement') {
      checklist.push(`Establish holding account: ${law.holdingAccount}`);
    }

    // Documentation
    checklist.push('Provide written receipt to tenant upon receiving deposit');
    checklist.push('Complete move-in inspection with tenant and document property condition');

    // Return deadline
    checklist.push(`Return deposit within ${law.returnDeadline}`);
    checklist.push('Provide itemized statement of any deductions');

    // Additional state-specific items
    if (law.notes) {
      if (law.notes.includes('written checklist')) {
        checklist.push('Provide written move-in and move-out checklists');
      }
      if (law.notes.includes('statement of condition')) {
        checklist.push('Provide statement of property condition');
      }
      if (law.notes.includes('forwarding address')) {
        checklist.push('Obtain tenant\'s forwarding address in writing');
      }
      if (law.notes.includes('account location')) {
        checklist.push('Notify tenant of deposit account location');
      }
    }

    // General best practices
    checklist.push('Keep detailed records of all deposit transactions');
    checklist.push('Take dated photos/videos at move-in and move-out');
    checklist.push('Review state law updates annually');

    return checklist;
  };

  const checklist = generateChecklist(law);

  const downloadChecklist = () => {
    // Generate text content
    const content = `
SECURITY DEPOSIT COMPLIANCE CHECKLIST
State: ${law.state} (${law.stateCode})
Generated: ${new Date().toLocaleDateString()}

============================================================
KEY REQUIREMENTS
============================================================

Maximum Deposit: ${law.maxDeposit}
Interest Required: ${law.interestRequired ? 'YES - ' + law.interestRate : 'NO'}
Return Deadline: ${law.returnDeadline}
Holding Account: ${law.holdingAccount}

PENALTIES FOR NON-COMPLIANCE:
${law.penalties}

============================================================
COMPLIANCE CHECKLIST (${checklist.length} items)
============================================================

${checklist.map((item, i) => `${i + 1}. [ ] ${item}`).join('\n')}

============================================================
IMPORTANT LEGAL DISCLAIMER
============================================================

This checklist is for informational purposes only and does not
constitute legal advice. Security deposit laws change frequently
and may have additional local requirements. Always consult with
a qualified attorney or local housing authority for specific
legal guidance.

Generated by Goldbridge Security Deposit Compliance Checker
    `.trim();

    // Create blob and download
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${law.state.replace(/\s+/g, '_')}_Security_Deposit_Checklist.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 p-6">
      <div className="flex items-center mb-4">
        <svg className="w-7 h-7 text-goldbridge-gold mr-3 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
        </svg>
        <h2 className="text-xl md:text-2xl font-bold text-slate-900 dark:text-white">
          Compliance Checklist for {law.state}
        </h2>
      </div>
      <p className="text-base text-slate-600 dark:text-slate-400 mb-5">
        Follow these steps to stay compliant with {law.state} security deposit laws
      </p>
      <div className="space-y-3">
        {checklist.map((item, index) => (
          <label
            key={index}
            className="flex items-start space-x-3 p-3 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700/50 cursor-pointer transition-colors group"
          >
            <input
              type="checkbox"
              className="mt-1 h-5 w-5 rounded border-slate-300 dark:border-slate-600 text-goldbridge-gold focus:ring-goldbridge-gold focus:ring-offset-0 cursor-pointer flex-shrink-0"
            />
            <span className="text-base text-slate-700 dark:text-slate-300 group-hover:text-slate-900 dark:group-hover:text-white flex-1 leading-relaxed">
              {item}
            </span>
          </label>
        ))}
      </div>
      <div className="mt-6 pt-6 border-t border-slate-200 dark:border-slate-700">
        <div className="flex items-center justify-between">
          <span className="text-base font-medium text-slate-600 dark:text-slate-400">
            {checklist.length} compliance items
          </span>
          <button
            onClick={downloadChecklist}
            className="px-5 py-2.5 bg-goldbridge-gold hover:bg-goldbridge-gold-dark text-white rounded-lg font-semibold transition-colors flex items-center space-x-2 shadow-sm hover:shadow-md"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span>Download Checklist</span>
          </button>
        </div>
      </div>
    </div>
  );
}
